/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/anomalias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Anomalías para revisión humana */
        get: operations["listar_anomalias_anomalias_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingreso con usuario y PIN */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/yo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuario de la sesión actual */
        get: operations["yo_auth_yo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalogos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Surtidores, productos y opciones de los formularios */
        get: operations["catalogos_catalogos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clientes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar y buscar clientes */
        get: operations["listar_clientes_clientes_get"];
        put?: never;
        /** Registrar un cliente desde la pista (exige la autorización de datos) */
        post: operations["crear_clientes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clientes/buscar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar un cliente por tipo y número de documento */
        get: operations["buscar_clientes_buscar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clientes/importar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Importar clientes desde CSV (en seco por defecto; exige autorización de datos con fecha) */
        post: operations["importar_clientes_csv_clientes_importar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clientes/{cliente_id}/activar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reactivar un cliente */
        post: operations["activar_cliente_clientes__cliente_id__activar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clientes/{cliente_id}/desactivar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Baja lógica: no se le factura ni aparece en la pista; se conserva su historial */
        post: operations["desactivar_cliente_clientes__cliente_id__desactivar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/despachos/pendientes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Despachos y ventas manuales pendientes de facturar (los más recientes primero) */
        get: operations["pendientes_despachos_pendientes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facturas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Emitir la factura de un despacho o venta manual (idempotente por `clave`) */
        post: operations["emitir_facturas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facturas/{factura_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado de una factura */
        get: operations["consultar_facturas__factura_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facturas/{factura_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Representación gráfica (PDF) de una factura validada, armada desde su XML */
        get: operations["pdf_facturas__factura_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publico/configuracion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lo que necesita la página pública de registro (captcha) */
        get: operations["configuracion_publica_publico_configuracion_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publico/registro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Autorregistro del cliente por QR (público, con límite de tasa)
         * @description Respuesta IGUAL si el documento ya estaba registrado: así no se puede averiguar quién es cliente.
         *     Un registro público nunca modifica los datos de un cliente existente.
         */
        post: operations["registro_publico_publico_registro_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reportes/contador": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ventas y facturas para la contabilidad (formato PROVISIONAL; lleva datos personales) */
        get: operations["contador_reportes_contador_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reportes/diario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ventas por día, producto y forma de pago */
        get: operations["diario_reportes_diario_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reportes/exportar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Excel de ventas de un surtidor (Diario, Mensual, Turnos, Datos, Alertas, Notas) */
        get: operations["exportar_reportes_exportar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reportes/mensual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ventas por mes, producto y forma de pago */
        get: operations["mensual_reportes_mensual_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reportes/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reporte diario, mensual o por turno en PDF (sin datos personales) */
        get: operations["reporte_pdf_reportes_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reportes/posibles-duplicados": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ventas manuales sin enlace que parecen ser un despacho ya contado (posible doble conteo) */
        get: operations["posibles_duplicados_reportes_posibles_duplicados_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reportes/turno": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resumen por turno (ID-CIERRE) y lado */
        get: operations["turno_reportes_turno_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** La API y la base responden (y la base tiene las migraciones) */
        get: operations["salud_salud_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuarios (para filtrar por vendedor) */
        get: operations["usuarios_usuarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehiculos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar y buscar vehículos */
        get: operations["listar_vehiculos_vehiculos_get"];
        put?: never;
        /** Registrar un vehículo o equipo de un cliente */
        post: operations["crear_vehiculo_vehiculos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehiculos/importar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Importar vehículos desde CSV (en seco por defecto; los dueños deben existir) */
        post: operations["importar_vehiculos_csv_vehiculos_importar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehiculos/{vehiculo_id}/activar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activar Vehiculo */
        post: operations["activar_vehiculo_vehiculos__vehiculo_id__activar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehiculos/{vehiculo_id}/desactivar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Desactivar Vehiculo */
        post: operations["desactivar_vehiculo_vehiculos__vehiculo_id__desactivar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ventas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar ventas (filtros de Nexus) con totales */
        get: operations["ventas_ventas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ventas-manuales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Venta digitada por el bombero (modo manual) */
        post: operations["crear_venta_manual_ventas_manuales_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnomaliaSalida */
        AnomaliaSalida: {
            /**
             * Creada En
             * Format: date-time
             */
            creada_en: string;
            /** Despacho Id Externo */
            despacho_id_externo: number | null;
            /** Detalle */
            detalle: {
                [key: string]: unknown;
            };
            /** Id */
            id: number;
            /** Resuelta */
            resuelta: boolean;
            /**
             * Severidad
             * @enum {string}
             */
            severidad: "ALTA" | "AVISO" | "INFO";
            /** Surtidor Id */
            surtidor_id: number | null;
            /** Tipo */
            tipo: string;
        };
        /** BusquedaVentasSalida */
        BusquedaVentasSalida: {
            /** Filas */
            filas: components["schemas"]["VentaSalida"][];
            /** Por Manguera */
            por_manguera: components["schemas"]["TotalMangueraSalida"][];
            /** @description del filtro completo, no solo de esta página */
            total: components["schemas"]["TotalesSalida"];
        };
        /** CaptchaSalida */
        CaptchaSalida: {
            /**
             * Clave Sitio
             * @description clave PÚBLICA del widget
             */
            clave_sitio: string;
            /**
             * Proveedor
             * @enum {string}
             */
            proveedor: "turnstile" | "hcaptcha";
        };
        /** CatalogosSalida */
        CatalogosSalida: {
            /** Medios Pago */
            medios_pago: string[];
            /** Productos */
            productos: components["schemas"]["ProductoSalida"][];
            /** Surtidores */
            surtidores: components["schemas"]["SurtidorSalida"][];
            /** Tipos Documento */
            tipos_documento: string[];
        };
        /** ClienteEntrada */
        ClienteEntrada: {
            /**
             * Apellidos
             * @default
             */
            apellidos: string;
            /**
             * Autoriza Tratamiento
             * @description autorización de tratamiento de datos (Ley 1581 de 2012)
             */
            autoriza_tratamiento: boolean;
            /**
             * Digito Verificacion
             * @description solo NIT; si falta se calcula
             */
            digito_verificacion?: string | null;
            /** Email */
            email: string;
            /**
             * Nombres
             * @description para NIT: razón social
             */
            nombres: string;
            /** Numero Documento */
            numero_documento: string;
            /**
             * Tipo Documento
             * @enum {string}
             */
            tipo_documento: "CC" | "NIT" | "NIT_EXTERIOR" | "CE" | "PA" | "PPT";
        };
        /** ClienteFactura */
        ClienteFactura: {
            /** Id */
            id: number;
            /** Nombre Mostrar */
            nombre_mostrar: string;
            /**
             * Tipo Documento
             * @enum {string}
             */
            tipo_documento: "CC" | "NIT" | "NIT_EXTERIOR" | "CE" | "PA" | "PPT";
        };
        /** ClienteSalida */
        ClienteSalida: {
            /** Activo */
            activo: boolean;
            /** Apellidos */
            apellidos: string;
            /** Digito Verificacion */
            digito_verificacion: string | null;
            /** Email Enmascarado */
            email_enmascarado: string;
            /** Id */
            id: number;
            /**
             * Nombre Mostrar
             * @description razón social si es NIT; nombres y apellidos si es persona
             */
            nombre_mostrar: string;
            /** Nombres */
            nombres: string;
            /** Numero Documento */
            numero_documento: string;
            /**
             * Tipo Documento
             * @enum {string}
             */
            tipo_documento: "CC" | "NIT" | "NIT_EXTERIOR" | "CE" | "PA" | "PPT";
        };
        /** ClientesPaginaSalida */
        ClientesPaginaSalida: {
            /** Filas */
            filas: components["schemas"]["ClienteSalida"][];
            /** Total */
            total: number;
        };
        /** ConfiguracionPublicaSalida */
        ConfiguracionPublicaSalida: {
            /** @description null: el registro no pide captcha (banco de pruebas) */
            captcha: components["schemas"]["CaptchaSalida"] | null;
            /** @description null: no hay una estación activa configurada */
            estacion: components["schemas"]["EstacionPublicaSalida"] | null;
        };
        /** Creado */
        Creado: {
            /** Id */
            id: number;
        };
        /** Error */
        Error: {
            /** Detail */
            detail: unknown;
        };
        /** EstacionPublicaSalida */
        EstacionPublicaSalida: {
            /**
             * Nombre
             * @description nombre comercial de la estación (o la razón social si no tiene)
             */
            nombre: string;
        };
        /** FacturaEntrada */
        FacturaEntrada: {
            /**
             * Clave
             * @description generada UNA vez por intento de emisión (p. ej. uuid sin guiones); reintentar con la misma clave no duplica la factura
             */
            clave: string;
            /** Cliente Id */
            cliente_id: number;
            /**
             * Medio Pago
             * @enum {string}
             */
            medio_pago: "EFECTIVO" | "TARJETA";
            /** Origen Id */
            origen_id: number;
            /**
             * Origen Tipo
             * @enum {string}
             */
            origen_tipo: "despacho" | "venta_manual";
        };
        /** FacturaSalida */
        FacturaSalida: {
            cliente: components["schemas"]["ClienteFactura"];
            /** Cufe */
            cufe: string | null;
            /** Error */
            error: string | null;
            /**
             * Estado
             * @enum {string}
             */
            estado: "EN_PROCESO" | "FACTURADO" | "RECHAZADO" | "INCIERTO";
            /**
             * Fecha Emision
             * Format: date-time
             */
            fecha_emision: string;
            /** Id */
            id: number;
            /**
             * Medio Pago
             * @enum {string}
             */
            medio_pago: "EFECTIVO" | "TARJETA";
            /**
             * Nueva
             * @description solo al emitir: False si la clave ya tenía factura
             */
            nueva?: boolean | null;
            /** Numero */
            numero: string;
            /** Origen Id */
            origen_id: number;
            /**
             * Origen Tipo
             * @enum {string}
             */
            origen_tipo: "despacho" | "venta_manual";
            /** Total */
            total: string;
        };
        /** FilaRechazadaSalida */
        FilaRechazadaSalida: {
            /**
             * Fila
             * @description línea del archivo (el encabezado es la 1)
             */
            fila: number;
            /** Problemas */
            problemas: string[];
        };
        /** FilaTurnoSalida */
        FilaTurnoSalida: {
            /** Despachos */
            despachos: number;
            /**
             * Estado
             * @enum {string}
             */
            estado: "ABIERTO" | "CERRADO";
            /**
             * Fin
             * Format: date-time
             */
            fin: string;
            /** Galones */
            galones: string;
            /** Id Cierre */
            id_cierre: number;
            /**
             * Inicio
             * Format: date-time
             */
            inicio: string;
            /** Lado */
            lado: string;
            /** Lectura Final Valor */
            lectura_final_valor: string | null;
            /** Lectura Final Vol */
            lectura_final_vol: string | null;
            /** Surtidor Id */
            surtidor_id: number;
            /** Turno Id */
            turno_id: number;
            /** Valor */
            valor: string;
        };
        /** FilaVentasSalida */
        FilaVentasSalida: {
            /** Despachos */
            despachos: number;
            /**
             * Forma Pago
             * @enum {string}
             */
            forma_pago: "CONTADO" | "CREDITO" | "OTRO";
            /** Galones */
            galones: string;
            /**
             * Origen
             * @description MANUAL: digitada en la pista, sin despacho enlazado
             * @enum {string}
             */
            origen: "SURTIDOR" | "MANUAL";
            /**
             * Periodo
             * Format: date
             */
            periodo: string;
            /** Producto */
            producto: string;
            /** Surtidor Id */
            surtidor_id: number;
            /** Valor */
            valor: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportacionSalida */
        ImportacionSalida: {
            /**
             * En Seco
             * @description true: solo se validó; no se guardó nada
             */
            en_seco: boolean;
            /**
             * Existentes
             * @description ya estaban registrados: no se modificaron
             */
            existentes: number;
            /** Filas */
            filas: number;
            /** Nuevas */
            nuevas: number;
            /** Rechazadas */
            rechazadas: components["schemas"]["FilaRechazadaSalida"][];
        };
        /** LoginEntrada */
        LoginEntrada: {
            /**
             * Pin
             * @example 1234
             */
            pin: string;
            /**
             * Usuario
             * @example bombero1
             */
            usuario: string;
        };
        /** PendienteSalida */
        PendienteSalida: {
            /**
             * Fecha
             * Format: date-time
             */
            fecha: string;
            /**
             * Forma Pago
             * @enum {string}
             */
            forma_pago: "CONTADO" | "CREDITO" | "OTRO";
            /** Lado */
            lado: string;
            /** Origen Id */
            origen_id: number;
            /**
             * Origen Tipo
             * @enum {string}
             */
            origen_tipo: "despacho" | "venta_manual";
            /** Placa */
            placa: string | null;
            /** Ppu */
            ppu: string;
            /** Producto */
            producto: string;
            /** Surtidor Id */
            surtidor_id: number;
            /** Valor */
            valor: string;
            /** Volumen */
            volumen: string;
        };
        /** PosibleDuplicadoSalida */
        PosibleDuplicadoSalida: {
            /** Despacho Id */
            despacho_id: number;
            /** Galones */
            galones: string;
            /**
             * Inicio Despacho
             * Format: date-time
             */
            inicio_despacho: string;
            /** Lado */
            lado: string;
            /** Producto */
            producto: string;
            /**
             * Registrada En
             * Format: date-time
             */
            registrada_en: string;
            /** Surtidor Id */
            surtidor_id: number;
            /** Valor */
            valor: string;
            /** Venta Manual Id */
            venta_manual_id: number;
        };
        /** ProductoSalida */
        ProductoSalida: {
            /** Codigo */
            codigo: string;
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
        };
        /** RegistroPublicoEntrada */
        RegistroPublicoEntrada: {
            /**
             * Apellidos
             * @default
             */
            apellidos: string;
            /**
             * Autoriza Tratamiento
             * @description autorización de tratamiento de datos (Ley 1581 de 2012)
             */
            autoriza_tratamiento: boolean;
            /**
             * Captcha
             * @description token del widget; obligatorio si la API tiene captcha configurado
             */
            captcha?: string | null;
            /**
             * Digito Verificacion
             * @description solo NIT; si falta se calcula
             */
            digito_verificacion?: string | null;
            /** Email */
            email: string;
            /**
             * Nombres
             * @description para NIT: razón social
             */
            nombres: string;
            /** Numero Documento */
            numero_documento: string;
            /**
             * Tipo Documento
             * @enum {string}
             */
            tipo_documento: "CC" | "NIT" | "NIT_EXTERIOR" | "CE" | "PA" | "PPT";
        };
        /** RegistroPublicoSalida */
        RegistroPublicoSalida: {
            /** Mensaje */
            mensaje: string;
        };
        /** SaludSalida */
        SaludSalida: {
            /**
             * Base De Datos
             * @constant
             */
            base_de_datos: "ok";
            /**
             * Estado
             * @constant
             */
            estado: "ok";
            /** Migracion */
            migracion: string | null;
        };
        /** SurtidorSalida */
        SurtidorSalida: {
            /** Codigo */
            codigo: string;
            /** Descripcion */
            descripcion: string | null;
            /** Id */
            id: number;
            /** Marca */
            marca: string;
        };
        /** TokenSalida */
        TokenSalida: {
            /** Access Token */
            access_token: string;
            /**
             * Expira En
             * @description segundos de validez del token
             */
            expira_en: number;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            usuario: components["schemas"]["UsuarioSalida"];
        };
        /** TotalMangueraSalida */
        TotalMangueraSalida: {
            /** Galones */
            galones: string;
            /** Lado */
            lado: string;
            /** Producto */
            producto: string;
            /** Surtidor Id */
            surtidor_id: number;
            /** Valor */
            valor: string;
            /** Ventas */
            ventas: number;
        };
        /** TotalesSalida */
        TotalesSalida: {
            /** Galones */
            galones: string;
            /** Valor */
            valor: string;
            /** Ventas */
            ventas: number;
        };
        /** UsuarioListadoSalida */
        UsuarioListadoSalida: {
            /** Activo */
            activo: boolean;
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /**
             * Rol
             * @enum {string}
             */
            rol: "BOMBERO" | "ADMIN";
            /** Usuario */
            usuario: string;
        };
        /** UsuarioSalida */
        UsuarioSalida: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /**
             * Rol
             * @enum {string}
             */
            rol: "BOMBERO" | "ADMIN";
            /** Usuario */
            usuario: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VehiculoEntrada */
        VehiculoEntrada: {
            /** Cliente Id */
            cliente_id: number;
            /** Descripcion */
            descripcion?: string | null;
            /**
             * Placa
             * @description placa o nombre del equipo; se normaliza
             */
            placa: string;
        };
        /** VehiculoSalida */
        VehiculoSalida: {
            /** Activo */
            activo: boolean;
            /** Cliente Id */
            cliente_id: number;
            /** Cliente Nombre */
            cliente_nombre: string;
            /** Descripcion */
            descripcion: string | null;
            /** Id */
            id: number;
            /** Identificador */
            identificador: string;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "PLACA" | "EQUIPO_TEXTO";
        };
        /** VehiculosPaginaSalida */
        VehiculosPaginaSalida: {
            /** Filas */
            filas: components["schemas"]["VehiculoSalida"][];
            /** Total */
            total: number;
        };
        /** VentaManualEntrada */
        VentaManualEntrada: {
            /**
             * Forma Pago
             * @default CONTADO
             * @enum {string}
             */
            forma_pago: "CONTADO" | "CREDITO";
            /**
             * Lado
             * @example A
             */
            lado: string;
            /** Ppu */
            ppu?: (number | string) | null;
            /**
             * Producto
             * @example CORRIENTE
             */
            producto: string;
            /** Surtidor Id */
            surtidor_id: number;
            /**
             * Valor
             * @example 29757
             */
            valor: number | string;
            /**
             * Volumen
             * @example 1.861
             */
            volumen: number | string;
        };
        /** VentaSalida */
        VentaSalida: {
            /** Cliente Documento */
            cliente_documento: string | null;
            /** Cliente Nombre */
            cliente_nombre: string | null;
            /** Cliente Tipo */
            cliente_tipo: ("CC" | "NIT" | "NIT_EXTERIOR" | "CE" | "PA" | "PPT") | null;
            /**
             * Estado Facturacion
             * @enum {string}
             */
            estado_facturacion: "PENDIENTE" | "EN_PROCESO" | "FACTURADO" | "INCIERTO" | "NO_FACTURABLE";
            /** Factura Estado */
            factura_estado: ("EN_PROCESO" | "FACTURADO" | "RECHAZADO" | "INCIERTO") | null;
            /** Factura Numero */
            factura_numero: string | null;
            /**
             * Fecha
             * Format: date-time
             */
            fecha: string;
            /**
             * Forma Pago
             * @enum {string}
             */
            forma_pago: "CONTADO" | "CREDITO" | "OTRO";
            /**
             * Id Externo
             * @description número del despacho en el surtidor (null en venta manual)
             */
            id_externo: number | null;
            /** Lado */
            lado: string;
            /** Origen Id */
            origen_id: number;
            /**
             * Origen Tipo
             * @enum {string}
             */
            origen_tipo: "despacho" | "venta_manual";
            /** Placa */
            placa: string | null;
            /** Producto */
            producto: string;
            /** Surtidor */
            surtidor: string;
            /** Surtidor Id */
            surtidor_id: number;
            /** Valor */
            valor: string;
            /** Vendedor */
            vendedor: string | null;
            /** Vendedor Id */
            vendedor_id: number | null;
            /** Volumen */
            volumen: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listar_anomalias_anomalias_get: {
        parameters: {
            query?: {
                estado?: "abiertas" | "resueltas" | "todas";
                severidad?: ("ALTA" | "AVISO" | "INFO") | null;
                limite?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnomaliaSalida"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenSalida"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Locked */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    yo_auth_yo_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioSalida"];
                };
            };
        };
    };
    catalogos_catalogos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogosSalida"];
                };
            };
        };
    };
    listar_clientes_clientes_get: {
        parameters: {
            query?: {
                /** @description inicio del documento o parte del nombre */
                texto?: string | null;
                estado?: "activos" | "inactivos" | "todos";
                limite?: number;
                desplazamiento?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientesPaginaSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_clientes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClienteEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteSalida"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    buscar_clientes_buscar_get: {
        parameters: {
            query: {
                tipo: "CC" | "NIT" | "NIT_EXTERIOR" | "CE" | "PA" | "PPT";
                numero: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteSalida"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    importar_clientes_csv_clientes_importar_post: {
        parameters: {
            query?: {
                en_seco?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /** @example tipo_documento;numero_documento;nombres;apellidos;email;autoriza_tratamiento;fecha_autorizacion */
                "text/csv": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportacionSalida"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    activar_cliente_clientes__cliente_id__activar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteSalida"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    desactivar_cliente_clientes__cliente_id__desactivar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cliente_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClienteSalida"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pendientes_despachos_pendientes_get: {
        parameters: {
            query?: {
                surtidor_id?: number | null;
                lado?: string | null;
                /** @description hora local de la estación */
                desde?: string | null;
                forma_pago?: "CONTADO" | "CREDITO" | "TODAS";
                limite?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendienteSalida"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    emitir_facturas_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FacturaEntrada"];
            };
        };
        responses: {
            /** @description la clave ya tenía factura (doble clic o reintento) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacturaSalida"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacturaSalida"];
                };
            };
            /** @description la venta ya no está pendiente o la clave se usó para otra venta */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description datos inválidos o caso todavía no soportado */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description falta configuración fiscal o numeración: no se emite */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    consultar_facturas__factura_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                factura_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacturaSalida"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pdf_facturas__factura_id__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                factura_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description representación gráfica (PDF) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description la factura todavía no está validada */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description el XML no permite armar la representación */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    configuracion_publica_publico_configuracion_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfiguracionPublicaSalida"];
                };
            };
        };
    };
    registro_publico_publico_registro_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistroPublicoEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistroPublicoSalida"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    contador_reportes_contador_get: {
        parameters: {
            query: {
                desde: string;
                hasta: string;
                formato?: "xlsx" | "csv" | "pdf";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": unknown;
                    "text/csv": unknown;
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diario_reportes_diario_get: {
        parameters: {
            query: {
                desde: string;
                hasta: string;
                surtidor_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilaVentasSalida"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exportar_reportes_exportar_get: {
        parameters: {
            query: {
                surtidor_id: number;
                desde: string;
                hasta: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mensual_reportes_mensual_get: {
        parameters: {
            query: {
                desde: string;
                hasta: string;
                surtidor_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilaVentasSalida"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reporte_pdf_reportes_pdf_get: {
        parameters: {
            query: {
                tipo: "diario" | "mensual" | "turno";
                desde: string;
                hasta: string;
                surtidor_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    posibles_duplicados_reportes_posibles_duplicados_get: {
        parameters: {
            query: {
                desde: string;
                hasta: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PosibleDuplicadoSalida"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    turno_reportes_turno_get: {
        parameters: {
            query: {
                desde: string;
                hasta: string;
                surtidor_id?: number | null;
                turno_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilaTurnoSalida"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    salud_salud_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaludSalida"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    usuarios_usuarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioListadoSalida"][];
                };
            };
        };
    };
    listar_vehiculos_vehiculos_get: {
        parameters: {
            query?: {
                /** @description parte de la placa */
                texto?: string | null;
                cliente_id?: number | null;
                estado?: "activos" | "inactivos" | "todos";
                limite?: number;
                desplazamiento?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehiculosPaginaSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_vehiculo_vehiculos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehiculoEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehiculoSalida"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    importar_vehiculos_csv_vehiculos_importar_post: {
        parameters: {
            query?: {
                en_seco?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /** @example placa;tipo_documento;numero_documento;descripcion */
                "text/csv": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportacionSalida"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    activar_vehiculo_vehiculos__vehiculo_id__activar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehiculo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehiculoSalida"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    desactivar_vehiculo_vehiculos__vehiculo_id__desactivar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehiculo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehiculoSalida"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ventas_ventas_get: {
        parameters: {
            query: {
                /** @description hora local, incluida */
                desde: string;
                /** @description hora local, excluida */
                hasta: string;
                /** @description equipo */
                surtidor_id?: number | null;
                lado?: string | null;
                producto?: string | null;
                forma_pago?: ("CONTADO" | "CREDITO" | "OTRO") | null;
                estado_facturacion?: ("PENDIENTE" | "EN_PROCESO" | "FACTURADO" | "INCIERTO" | "NO_FACTURABLE") | null;
                /** @description parte de la placa */
                placa?: string | null;
                /** @description número de documento */
                cliente?: string | null;
                /** @description número del despacho en el surtidor */
                id_externo?: number | null;
                /** @description número completo, p. ej. SETP1 */
                factura?: string | null;
                vendedor_id?: number | null;
                limite?: number;
                desplazamiento?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusquedaVentasSalida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_venta_manual_ventas_manuales_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VentaManualEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Creado"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
